# Development-focused Docker Compose configuration
# This file is optimized for local development with hot-reloading
# The database service connects to Supabase instead of using a local PostgreSQL database

version: '3.8'

services:
  database:
    build:
      context: ./services/database
      target: development  # Use development target by default
    container_name: navi_cfci-database
    ports:
      - "5001:5001"
    env_file:
      - ./services/database/.env    # Contains Supabase connection string
    volumes:
      - ./services/database/src:/app/src  # Mount only source code for hot-reloading
      - ./services/database/prisma:/app/prisma  # Mount prisma directory
      - ./services/database/package.json:/app/package.json  # Mount package.json
      - ./services/database/tsconfig.json:/app/tsconfig.json  # Mount tsconfig.json
      - ./services/database/.env:/app/.env  # Mount .env file directly
      # Exclude the dist directory to keep the built files
    environment:
      - NODE_ENV=development

  api_gateway:
    build:
      context: ./services/api_gateway
      target: development
    container_name: navi_cfci-api_gateway
    volumes:
      - ./services/api_gateway:/app
      - /app/node_modules
    ports:
      - "8000:8000"
    depends_on:
      - interview_analysis
      - database
      - sprint1_deprecated
    env_file:
      - ./services/api_gateway/.env
    environment:
      - SERVICE_INTERVIEW_ANALYSIS=http://interview_analysis:8001
      - SERVICE_DATABASE=http://database:5001
      - SERVICE_SPRINT1_DEPRECATED=http://sprint1_deprecated:8002
      - NODE_ENV=development
      - DEBUG=true
      - ENABLE_DEV_AUTH=true
      - ALLOW_HEADER_PASSTHROUGH=true
      - TRUSTED_ORIGINS=http://localhost:3000,http://frontend:3000
      - DEVELOPMENT_USER_ID=dev-user-123

  interview_analysis:
    build:
      context: ./services/interview_analysis
      target: development
    container_name: navi_cfci-interview_analysis
    volumes:
      - ./services/interview_analysis:/app
      - /app/node_modules
    ports:
      - "8001:8001"
    env_file:
      - ./services/interview_analysis/.env
    environment:
      - NODE_ENV=development

  sprint1_deprecated:
    build:
      context: ./services/sprint1_deprecated
      target: development
    container_name: navi_cfci-sprint1_deprecated
    volumes:
      - ./services/sprint1_deprecated:/app
      - /app/node_modules
    ports:
      - "8002:8002"
    env_file:
      - ./services/sprint1_deprecated/.env
    environment:
      - NODE_ENV=development

  frontend:
    build:
      context: ./frontend
      target: development
    container_name: navi_cfci-frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - api_gateway
      - database

volumes:
  api_gateway_logs:
  interview_analysis_logs:
  sprint1_deprecated_logs: 