# Development-focused Docker Compose configuration
# This file is optimized for local development with hot-reloading
# The database service connects to Supabase instead of using a local PostgreSQL database

services:
  database-service:
    build:
      context: ./services/database-service
      target: development  # Use development target by default
    ports:
      - "5001:5001"
    env_file:
      - ./services/database-service/.env    # Contains Supabase connection string
    environment:
      - NODE_ENV=development # Explicitly set NODE_ENV for entrypoint.sh logic
    volumes:
      - ./services/database-service/src:/app/src  # Mount only source code for hot-reloading
      - ./services/database-service/prisma:/app/prisma  # Mount prisma directory
      - ./services/database-service/package.json:/app/package.json  # Mount package.json
      - ./services/database-service/tsconfig.json:/app/tsconfig.json  # Mount tsconfig.json
      - ./services/database-service/.env:/app/.env  # Mount .env file directly
      # Exclude the dist directory to keep the built files
    # Migration and dev server start are now handled by entrypoint.sh, triggered by default.

  api_gateway:
    build:
      context: ./services/api_gateway
      target: development
    volumes:
      - ./services/api_gateway:/app
      - /app/node_modules
    ports:
      - "8000:8000"
    depends_on:
      - interview_analysis
      - database-service
      - sprint1_deprecated
    env_file:
      - ./services/api_gateway/.env

  interview_analysis:
    build:
      context: ./services/interview_analysis
      target: development
    volumes:
      - ./services/interview_analysis:/app
      - /app/node_modules
    ports:
      - "8001:8001"
    env_file:
      - ./services/interview_analysis/.env

  sprint1_deprecated:
    build:
      context: ./services/sprint1_deprecated
      target: development
    volumes:
      - ./services/sprint1_deprecated:/app
      - /app/node_modules
    ports:
      - "8002:8002"
    env_file:
      - ./services/sprint1_deprecated/.env

  frontend:
    build:
      context: ./frontend
      target: development
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    depends_on:
      - api_gateway