steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/sprint1-deprecated', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/sprint1-deprecated']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'sprint1-deprecated'
      - '--image=gcr.io/$PROJECT_ID/sprint1-deprecated'
      - '--region=us-central1'
      - '--platform=managed'
      - '--service-account=sprint1-deprecated@$PROJECT_ID.iam.gserviceaccount.com'
      - '--no-allow-unauthenticated'
      - '--update-secrets=OPENAI_API_KEY=openai-api-key:latest'
      - '--set-env-vars=NODE_ENV=${_NODE_ENV}'
      - '--set-env-vars=DEBUG=${_DEBUG}'
      - '--set-env-vars=LOG_LEVEL=${_LOG_LEVEL}'
      - '--cpu=1'
      - '--memory=512Mi'
      - '--timeout=600s'
      - '--min-instances=0'
      - '--max-instances=2'
      - '--cpu-boost'
      
images:
  - 'gcr.io/$PROJECT_ID/sprint1-deprecated'

# Default substitutions - can be overridden during deployment
substitutions:
  _NODE_ENV: production
  _DEBUG: "false"
  _LOG_LEVEL: INFO 