steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/interview-analysis', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/interview-analysis']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'interview-analysis'
      - '--image=gcr.io/$PROJECT_ID/interview-analysis'
      - '--region=us-central1'
      - '--platform=managed'
      - '--service-account=interview-analysis@$PROJECT_ID.iam.gserviceaccount.com'
      - '--no-allow-unauthenticated'
      - '--update-secrets=GEMINI_API_KEY=gemini-api-key:latest'
      - '--set-env-vars=DATABASE_API_URL=${_DATABASE_API_URL}'
      - '--set-env-vars=NODE_ENV=${_NODE_ENV}'
      - '--set-env-vars=DEBUG=${_DEBUG}'
      - '--set-env-vars=CORS_ORIGINS=${_CORS_ORIGINS}'
      - '--set-env-vars=API_GATEWAY_URL=${_API_GATEWAY_URL}'
      - '--set-env-vars=LOG_LEVEL=${_LOG_LEVEL}'
      - '--cpu=1'
      - '--memory=512Mi'
      - '--timeout=600s'
      - '--min-instances=0'
      - '--max-instances=2'
      - '--cpu-boost'
      
images:
  - 'gcr.io/$PROJECT_ID/interview-analysis'

# Default substitutions - can be overridden during deployment
substitutions:
  _DATABASE_API_URL: https://database-service-821475546424.us-central1.run.app
  _NODE_ENV: production
  _DEBUG: "false"
  _CORS_ORIGINS: https://navi-cfci.vercel.app
  _API_GATEWAY_URL: https://api-gateway-821475546424.us-central1.run.app
  _LOG_LEVEL: INFO 