steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/api-gateway', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/api-gateway']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'api-gateway'
      - '--image'
      - 'gcr.io/$PROJECT_ID/api-gateway'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--service-account'
      - 'api-gateway@$PROJECT_ID.iam.gserviceaccount.com'
      - '--set-env-vars=SERVICE_INTERVIEW_ANALYSIS=${_SERVICE_INTERVIEW_ANALYSIS}'
      - '--set-env-vars=SERVICE_DATABASE=${_SERVICE_DATABASE}'
      - '--set-env-vars=NODE_ENV=${_NODE_ENV}'
      - '--set-env-vars=DEBUG=${_DEBUG}'
      - '--set-env-vars=LOG_LEVEL=${_LOG_LEVEL}'
      - '--set-env-vars=CORS_ORIGINS=${_CORS_ORIGINS}'
      - '--set-env-vars=ENABLE_DEV_AUTH=${_ENABLE_DEV_AUTH}'
      - '--update-secrets=JWT_SECRET=nextauth-jwt-secret:latest'

images:
  - 'gcr.io/$PROJECT_ID/api-gateway'

# Default substitution values - can be overridden when submitting the build
substitutions:
  _SERVICE_INTERVIEW_ANALYSIS: ''
  _SERVICE_DATABASE: ''
  _NODE_ENV: 'production'
  _DEBUG: 'false'
  _LOG_LEVEL: 'INFO'
  _CORS_ORIGINS: 'https://navi-cfci.vercel.app'
  _ENABLE_DEV_AUTH: 'false' 