steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/api-gateway', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/api-gateway']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'api-gateway'
      - '--image'
      - 'gcr.io/$PROJECT_ID/api-gateway'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--service-account'
      - 'api-gateway@$PROJECT_ID.iam.gserviceaccount.com'
      - '--set-env-vars'
      - 'SERVICE_INTERVIEW_ANALYSIS=${_SERVICE_INTERVIEW_ANALYSIS},SERVICE_DATABASE=${_SERVICE_DATABASE},SERVICE_SPRINT1_DEPRECATED=${_SERVICE_SPRINT1_DEPRECATED},NODE_ENV=production,DEBUG=false,LOG_LEVEL=INFO,CORS_ORIGINS=https://navi-cfci.vercel.app,ENABLE_DEV_AUTH=false,ALLOW_X_USER_ID_HEADER=True'
      - '--update-secrets'
      - 'JWT_SECRET=nextauth-jwt-secret:latest'

images:
  - 'gcr.io/$PROJECT_ID/api-gateway'

# Default substitution values - can be overridden when submitting the build
substitutions:
  _SERVICE_INTERVIEW_ANALYSIS: 'https://interview-analysis-821475546424.us-central1.run.app'
  _SERVICE_DATABASE: 'https://database-service-821475546424.us-central1.run.app'
  _SERVICE_SPRINT1_DEPRECATED: 'https://sprint1-deprecated-821475546424.us-central1.run.app' 